### ISSUE TITLE
Test basic auth

### ISSUE THREAD

**Issue by ir4y** [hl7au/au-fhir-core-inferno#1]
The launch form requires an access token, we need to make sure that it also works with basic auth

**Comment by projkov** [comment]
According to the documentation, it does not support basic authentication. There are two ways to use tokens:

1. Utilize the oauth_credentials input type, which is currently available.
2. Enter the token into a text field and then pass it to the bearer_token attribute in the test suite.

**Comment by projkov** [comment]
We can implement a temporary solution by setting an environment variable with the token and passing it through the headers in the "configure fhir_client" step. 

Also, we can make a "feature request" to the team or try to implement it by our hands and make a pull request.
