### ISSUE TITLE
Encounter tests missing for SHOULD requirements

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core-inferno#100]
There is no test for a SHOULD patient.identifier search parameter requirement.

**Comment by projkov** [comment]
@heathfrankel

This problem was fixed. New tests will be appear right after the deploy to the server.

**Comment by heathfrankel** [comment]
I can see there are now new tests for search parameter  Patient.identifier, but there is no data available to test.
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/5aad9017-b17e-4e97-a2a0-6033bb8c4534)

@projkov why is there no data to perform search?
I know that Patient/bennelong-anne and Patient/smith-emma have a Medicare card identifier,
Patient/baldry-terence has an IHI identifier, and
Patient/dan-harry has a DVA identifier
Patient/baby-smith-john has an identifier of type MR

@projkov if these are not sufficient what data do we need to be able to get a successful test?

**Comment by projkov** [comment]
@heathfrankel Hello Heath

Could you review this ticket one more time? It should be fixed.

I have successfully tested it here. IHI is an issue in my case because the tested patient doesn't have it.

https://inferno.hl7.org.au/au_core_v040_ci_build/ezUqBHX0hHB#au_core_v040_ci_build/report
