### ISSUE TITLE
Encounter tests - unclear meaning of result

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core-inferno#103]
Got the following test result, but it is not clear what I can do to fix this. 
Need further guidance, but I suspect that there is data missing in the reference server? 
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/3ae9d0ff-f005-4d33-96e4-e348fae5180b)

**Comment by projkov** [comment]
@heathfrankel hello Heath

This message indicates that the 11 Encounter resources found by the search request do not have an identifier attribute. I verified this with a request via Postman, and it is accurate.

To resolve this issue, you need to add an identifier attribute to at least one of the Encounter resources on the server side.

Do you have any ideas on how we can make this message more informative?

Here is a suggestion:

"Could not find the identifier attribute in the 11 Encounter resource(s) provided. To prevent this issue, please add the missing identifier attribute to at least one Encounter resource on the server."

What do you think?

**Comment by heathfrankel** [comment]
Agree with the suggested change except to use the term "element" instead of attribute.
Perhaps highlight the element name in italics or quotes to distinguish it as an element name 
E.g. 

"Could not find the _identifier_ element in the 11 Encounter resource(s) provided. To prevent this issue, please add the missing must support elements to at least one Encounter resource on the server."

**Comment by projkov** [comment]
Hello @heathfrankel 
Could you review it one more time?
