### ISSUE TITLE
README missing how to provide feedback / raise defects

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#108]
Add to the README on how to contribute feedback / raise defects, and the zulip channel to ask questions. See AU Core's README for the template: https://github.com/hl7au/au-fhir-core?tab=readme-ov-file#readme

The channel for AU Core Testing is https://chat.fhir.org/#narrow/stream/179173-australia/topic/AU.20Core.20Testing

**Comment by projkov** [comment]
Hello Danielle @dt-r 

What do you think about this new section in the README? (https://github.com/hl7au/au-fhir-core-inferno/tree/108-add-feedback-readme?tab=readme-ov-file#reporting-issues). It's not merged yet. I think it covers all questions from users who want to create an issue or ask a question: where users can check existing issues and how to raise an issue. Also, this section has the link to the topic in Zulip.

I can change the text or add more details if you want.

**Comment by dt-r** [comment]
That's fine. This can now be closed.
