### ISSUE TITLE
Validation warning for the valid resource.

### ISSUE THREAD

**Issue by projkov** [hl7au/au-fhir-core-inferno#110]
The validation test for the AllergyIntolerance resource returns an incorrect warning related to the terminology.

For example, we can use this resource:
```json
{
    "resourceType": "AllergyIntolerance",
    "id": "wasp",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2024-03-06T15:30:47.422+00:00",
        "profile": [
            "http://hl7.org.au/fhir/core/StructureDefinition/au-core-allergyintolerance"
        ]
    },
    "clinicalStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical",
                "code": "active",
                "display": "Active"
            }
        ]
    },
    "verificationStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification",
                "code": "unconfirmed",
                "display": "Unconfirmed"
            }
        ]
    },
    "category": [
        "environment"
    ],
    "code": {
        "coding": [
            {
                "system": "http://snomed.info/sct",
                "code": "256440004",
                "display": "Wasp venom"
            }
        ]
    },
    "patient": {
        "reference": "Patient/dan-harry"
    },
    "recordedDate": "2023-09-05",
    "asserter": {
        "reference": "PractitionerRole/bobrester-bob-gp"
    },
    "reaction": [
        {
            "substance": {
                "coding": [
                    {
                        "system": "http://snomed.info/sct",
                        "code": "256440004",
                        "display": "Wasp venom"
                    }
                ]
            },
            "manifestation": [
                {
                    "coding": [
                        {
                            "system": "http://snomed.info/sct",
                            "code": "247472004",
                            "display": "Hives"
                        }
                    ]
                },
                {
                    "coding": [
                        {
                            "system": "http://snomed.info/sct",
                            "code": "418363000",
                            "display": "Itching of skin"
                        }
                    ]
                },
                {
                    "coding": [
                        {
                            "system": "http://snomed.info/sct",
                            "code": "76067001",
                            "display": "Sneezing"
                        }
                    ]
                }
            ]
        }
    ]
}
```

At the current time, the validator returns these problems related to the resource:

1. AllergyIntolerance/wasp: AllergyIntolerance.reaction[0].manifestation[0]: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1 not found
2. AllergyIntolerance/wasp: AllergyIntolerance.reaction[0].manifestation[1]: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1 not found
3. AllergyIntolerance/wasp: AllergyIntolerance.reaction[0].manifestation[2]: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1 not found
4. AllergyIntolerance/wasp: AllergyIntolerance.reaction[0].substance: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/adverse-reaction-agent-1 not found
5. AllergyIntolerance/wasp: AllergyIntolerance.code: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2 not found
6. AllergyIntolerance/wasp: AllergyIntolerance: Constraint failed: dom-6: 'A resource should have narrative for robust management' (defined in http://hl7.org/fhir/StructureDefinition/DomainResource) (Best Practice Recommendation)

But if we check this code: 247472004 (which is used in the AllergyIntolerance.reaction[0].manifestation[0]), we will find it is correct because it exists in the SNOMED CT refset.

@StephThaoOng originally reported the issue.

**Comment by mjosborne1** [comment]
There was an issue with an expired NCTS token/secret on the server which got fixed. Is this test still failing?

**Comment by StephThaoOng** [comment]
> sue with an e

Hi @mjosborne1 I've just run the AllergyIntolerance 1.13.09 test again and the same validation warnings are still displayed.

**Comment by mjosborne1** [comment]
These ValueSets are all present on the tx.dev server, but there are multiple active ValueSets with the same URL and different versions. Would thi pose a problem for the tests?
e.g.
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/693010/61cb15d4-d722-418b-ad37-e06e6c1779b2)

**Comment by StephThaoOng** [comment]
Same warnings are returned on testing [Using the FHIR Validator Locally](https://confluence.hl7.org/display/HA/Quick+Guide%3A+Using+the+FHIR+Validator+Locally) with tx.dev, and on a AU Core 0.4.0-ci-build qa report. 
This means it is likely a tx.dev issue or validator issue, and not due to Inferno.

**Comment by mjosborne1** [comment]
Grahame will look at it...https://chat.fhir.org/#narrow/stream/179167-hapi/topic/External.20Terminology.20server

**Comment by mjosborne1** [comment]
Grahame confirmed on Zulip that there's a bug in the validator code and it will be fixed in the next release.

**Comment by StephThaoOng** [comment]
Need to ensure that Inferno uses the latest FHIR validator.

**Comment by michael-wilson-au** [comment]
The latest version of the FHIR Validator has now been released ([6.3.11](https://github.com/hapifhir/org.hl7.fhir.core/releases/tag/6.3.11)) with a fix for this issue.

I have confirmed via Validator CLI that it correctly uses tx.dev.hl7.org.au to validate valuesets

`java -jar validator_cli.jar AllergyIntolerance.json -tx http://tx.dev.hl7.org.au/fhir/ -version 4.0 -txLog txLog.txt`
`Success: 0 errors, 1 warnings, 5 notes
  Information @ AllergyIntolerance.code (line 32, col4): None of the codings provided are in the value set 'Indicator of Hypersensitivity or Intolerance to Substance' (https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2|2.1.0), and a coding is recommended to come from this value set (codes = http://snomed.info/sct#256440004)
  Information @ AllergyIntolerance.reaction[0].substance (line 50, col8): None of the codings provided are in the value set 'Adverse Reaction Agent' (https://healthterminologies.gov.au/fhir/ValueSet/adverse-reaction-agent-1|1.1.1), and a coding is recommended to come from this value set (codes = http://snomed.info/sct#256440004)
  Information @ AllergyIntolerance.reaction[0].manifestation[0] (line 60, col10): None of the codings provided are in the value set 'Clinical Finding' (https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1|1.0.2), and a coding is recommended to come from this value set (codes = http://snomed.info/sct#247472004)
  Information @ AllergyIntolerance.reaction[0].manifestation[1] (line 69, col10): None of the codings provided are in the value set 'Clinical Finding' (https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1|1.0.2), and a coding is recommended to come from this value set (codes = http://snomed.info/sct#418363000)
  Information @ AllergyIntolerance.reaction[0].manifestation[2] (line 78, col10): None of the codings provided are in the value set 'Clinical Finding' (https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1|1.0.2), and a coding is recommended to come from this value set (codes = http://snomed.info/sct#76067001)
  Warning @ AllergyIntolerance (line 1, col2): Constraint failed: dom-6: 'A resource should have narrative for robust management' (defined in http://hl7.org/fhir/StructureDefinition/DomainResource) (Best Practice Recommendation)`

**Comment by projkov** [comment]
@StephThaoOng Hello Steph

I asked the Inferno team about the validator, and they informed me that it's not just a simple configuration change. However, we know how to fix it, and it will be resolved.

**Comment by projkov** [comment]
It may be a problem related to caching the first validation result.

Details are available in the email from July 15th.
