### ISSUE TITLE
Location tests - retrieve more Location resources from the reference server to run optional tests 

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#113]
Currently, the Location test suite starts with one search request: https://sparked.npd.telstrahealth.com/smile/fhir/DEFAULT/Location/patient-home
As a result, tests 1.19.02, 1.19.04 - 1.19.07, 1.19.09 are skipped.

For the default search requests from the Sparked FHIR server, please retrieve more Location resources in order to run the optional tests. 

Version tested: AU Core v0.4.0-ci-build v.0.0.5

**Comment by projkov** [comment]
@StephThaoOng Hello
Maybe we don't need to create a new one. Would it be better to update the existing one?

**Comment by StephThaoOng** [comment]
Hi @projkov what first search would you recommend to enable the subsequent tests to run? Or do you mean add more data to the Location/patient-home resource?
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/36804832/56da26f4-a2df-496b-b83a-79f52880b5dd)

**Comment by projkov** [comment]
@StephThaoOng Hello Steph!
I want to suggest adding more data to the Location resource (patient-home)

**Comment by StephThaoOng** [comment]
> @StephThaoOng Hello Steph! I want to suggest adding more data to the Location resource (patient-home)

@projkov thanks Pavel, I'll add more data to Location resource (patient-home).
