### ISSUE TITLE
Location tests - Testing Methodology > Searching > Search Parameters description query

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#114]
In the Testing Methodology > Searching > Search Parameters section, the first sentence reads:
"The first search uses the selected patient(s) from the prior launch sequence."

Is this correct? 
If not, please consider updating this description.

Version tested: AU Core v0.4.0-ci-build v.0.0.5

**Comment by projkov** [comment]
@StephThaoOng Hello Steph!

This problem also exists for the Practitioner, PractitionerRole, and Organization tests. I suggest using the following text:

"Resources for this test group can’t be found using patient search parameters. This means that, in this particular case, the first test will be a read test, not a search. To ensure that this resource will be available for reading, please review the [prerequisites](https://github.com/hl7au/au-fhir-core-inferno/blob/master/docs/pre-requisites.md). Additionally, you can run this test group separately by using specific resource IDs."

If you agree, please confirm, and I will close this issue and merge the changes into the master branch.

**Comment by StephThaoOng** [comment]
> @StephThaoOng Hello Steph!
> 
> This problem also exists for the Practitioner, PractitionerRole, and Organization tests. I suggest using the following text:
> 
> "Resources for this test group can’t be found using patient search parameters. This means that, in this particular case, the first test will be a read test, not a search. To ensure that this resource will be available for reading, please review the [prerequisites](https://github.com/hl7au/au-fhir-core-inferno/blob/master/docs/pre-requisites.md). Additionally, you can run this test group separately by using specific resource IDs."
> 
> If you agree, please confirm, and I will close this issue and merge the changes into the master branch.

Thanks @projkov. This looks good - I agree.

**Comment by projkov** [comment]
The fix is available on production in version 0.0.12. The issue can be closed.
