### ISSUE TITLE
onset-date search for the condition is not working

### ISSUE THREAD

**Issue by projkov** [hl7au/au-fhir-core-inferno#115]
The onset-date search said that there is no data to run the test, but this data definitely exists in the demo resources. The problem is related to the automatically generated search definition in the Condition's manifest. 

It should be fixed.

**Comment by StephThaoOng** [comment]
Thanks @projkov .

- [ ] For Condition test: _1.14.05 Optional (MAY) Server returns valid results for Condition search by onset-date_, there seems to be a duplicate test for the gt date comparator as shown below. 
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/36804832/c80a81dc-34c2-45af-a7cd-ccf8dae29e85)
Perhaps the first search is suppose to be a onset-date search precise to the second + time offset without a date comparator.

- [ ] For Condition test: _1.14.10 Optional (SHOULD) Server returns valid results for Condition search by patient + onset-date_, 

1. first two tests seem to be duplicates as shown below.
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/36804832/c01ab7c4-315f-4522-89e8-1fa4326a9e6a)
2. Can we include a patient search [base]/Condition?patient=Patient/[id] when combined with with onset-date search parameter
3. Can we include patient.identifier search when combined with onset-date search parameter
4. Can we include the multipleAND search on onset-date when combined with patient search parameter, both without and with date comparators

- [ ] I will follow up about test _14.11 Optional (SHOULD) Server returns valid results for Condition multipleAnd search by onset-date_ error: "HAPI-1922: Can not have multiple date range parameters for the same param without a qualifier".
It seems the Sparked FHIR server currently does not meet the search by patient+onset-date SHOULD conformance expectation defined in AU Core. If you have any insights, please let me know :)

**Comment by StephThaoOng** [comment]
thanks Pavel.

- [ ] Search for Condition by **onset-date** test 1.14.05 - first two tests seem to be duplicates (same 'gt' date comparator)' please replace one with a test precise to the second + time offset without comparators.
- [ ] Search for Condition by **patient+onset-date** test 1.14.10 

   - [ ] first two tests are duplicates (same patient, date and 'gt' comparator)'
   - [ ] missing chained patient.identifier search test
   - [ ] missing multipleAnd search on onset-date both with and without date comparators for the combined search with the patient param

- [ ] Search for Condition by **multipleAND** search on **onset-date** test 1.14.11 - consider adding a test using date comparators too.
   - [ ] I'll follow up re: HAPI error "_"diagnostics": "HAPI-1922: Can not have multiple date range parameters for the same param without a qualifier"_". If this can't be fixed, it seems like the server would not meet this SHOULD conformance expectation.

**Comment by projkov** [comment]
@StephThaoOng 

I conducted research related to the problem of the double "gt" test. This functionality exists for some reason in the US Core Test Kit. To fix this problem, we need more time.

I suggest creating a separate task for it and making this enhancement after the 25th. I think it's not a "showstopper."

**Comment by projkov** [comment]
@StephThaoOng Hello Steph!

multipleOr and multipleAnd tests with date are fixed (comparators are added)
