### ISSUE TITLE
Add a Organisation.identifier search test for HPI-O

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#116]
For the Organisation tests, one of the test cases for the identifier search parameter is: 

The responder SHOULD support searching for an organisation when supplied with both the HPI-O system an identifier value.

In test 1.20.04, I can see a search request using the ABN identifier (as shown below), but there doesn't seem to be one for the HPI-O identifier. Also, search by ABN and HPI-O have a conformance level of SHOULD, so are optional tests. 
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/36804832/2452d36a-8e23-4cde-95a4-780d423d17b2)

Version tested: AU Core v0.4.0-ci-build V.0.0.5

**Comment by projkov** [comment]
@StephThaoOng Hello
We have new special tests for Organization identifiers.

**Comment by StephThaoOng** [comment]
@projkov I see a test for search by ABN identifier, but still missing search by HPI-O identifier (system=http://ns.electronichealth.net.au/id/hi/hpio/1.0)

Version tested: AU Core v0.4.0-ci-build V.0.0.7
