### ISSUE TITLE
Add a PractitionerRole search by practitioner search parameter test

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#120]
Add a test to the practitioner_role_practitioner_search test to cover:

- The responder SHALL support searching for PractitionerRole by PRACTITIONER search parameter when supplied with an id value only. 
i.e. GET [base]/PractitionerRole?practitioner=[id]

Version tested: AU Core v0.4.0-ci-build V.0.0.5

**Comment by projkov** [comment]
Hello @StephThaoOng 
Could you review it one more time? If all is good, could you close this ticket?

Thanks!

**Comment by StephThaoOng** [comment]
Hi @projkov I still can't see that test being added to meet
"The requester SHALL provide at least an **_id_** value and MAY provide both the **_Type and id_** values. **_The responder SHALL support both._**" i.e. we should have two tests for search by practitioner search param:

   1. GET [base]/PractitionerRole?practitioner=[id]
   2. GET [base]/PractitionerRole?practitioner={Type/}[id]

**Comment by projkov** [comment]
@StephThaoOng Hello Steph. We have this test.

![Image](https://github.com/hl7au/au-fhir-core-inferno/assets/4172228/fec1f9e9-2329-4e72-b15b-cf6bb5eb1924)

**Comment by StephThaoOng** [comment]
@projkov thanks - sorry I must've missed this. Closing ticket now. Thanks
