### ISSUE TITLE
Add a PractitionerRole search by identifier search parameter test (optional/SHOULD)

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#121]
Add an optional (SHOULD) test to the practitioner_role_identifier_search test to cover:

- The responder SHALL support searching for PractitionerRole when supplied with both the Medicare Provider Number system and an identifier value.

Version tested: AU Core v0.4.0-ci-build V.0.0.5

**Comment by projkov** [comment]
@StephThaoOng Hello Steph.
Update is available on the server

**Comment by StephThaoOng** [comment]
Sorry @projkov 
It was suppose to be a SHOULD i.e. optional test, and 
the system=http://ns.electronichealth.net.au/id/medicare-provider-number

![Image](https://github.com/hl7au/au-fhir-core-inferno/assets/36804832/809464cc-c531-4a95-be0b-1bf8ef4a96fe)

**Comment by projkov** [comment]
@StephThaoOng all good. I made it an optional test with http://ns.electronichealth.net.au/id/medicare-provider-number

![Image](https://github.com/hl7au/au-fhir-core-inferno/assets/4172228/f4a8ff6f-0077-4cd1-bee6-c11c5a14f1dc)
