### ISSUE TITLE
Limited Location resources retrieved to run all tests

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#144]
Hi @projkov 
Only one Location resource is retrieved to run tests. 
As previously discussed, I cannot update the Location/patient-home resource as its Location.mode="kind"
Besides, this seems to be an Inferno issue rather than a test data issue.
There are at least three other Location resources on the default server that I think should have been retrieved previously for the default patient's Encounters, Procedures, and Immunizations. These are:
- Location/murrabit-hospital
- Location/au-hospital
- Location/bobrester-medical-center

I will linking more Location resources to the default patient's Procedures and Encounters but not confident that the way the Inferno tests scripts are structured and generated will actually solve the issue. 
Furthermore, the Location test suite does not support retrieving Location resources referenced in Practitioner, PractitionerRole, Organization resources which is limiting.

Please uplift the Location test suite.

**Comment by projkov** [comment]
@StephThaoOng Hello Steph,

Thank you for the research.

I did some research myself on this problem and found that in the current implementation, Inferno gets location resources from the encounters identified in the Encounter tests. This means that Location/au-hospital and Location/patient-home should be present as items for read.

I also discovered that the read tests use only one resource to run any read test. 

I have made a change, and it will be available in production soon.

**Comment by projkov** [comment]
@StephThaoOng 

The same is true for tests related to the Practitioner resource. To fix this, you need to add a practitioner as a reference to at least one Observation linked to the patients whose IDs are used as input for the test kit. This should help...

**Comment by StephThaoOng** [comment]
@projkov thanks! 
Yes results are better now. 
Interesting that Inferno only gets Location resources referenced in the Encounter set. 
Our Encounter test data now includes another 2 referenced Locations (so 4 in total). 

I've added a Practitioner reference to an Observation resource. 

Updated test data will be loaded to the default server tomorrow.  

Please track these dependencies so we can add them to user guides and documentation, or include in the README.

I'll close this ticket now but please raise a separate ticket for enhancements to remove these unexpected dependencies and improve the testing of resources that are not linked to the patient directly.
