### ISSUE TITLE
Document the Inferno AU Core Test dependencies/pre-requisites in the README for user awareness

### ISSUE THREAD

**Issue by projkov** [hl7au/au-fhir-core-inferno#152]
1. E.g. for Practitioner tests, ensure Practitioner is referenced in at least one Observation linked to the patients whose IDs are used as input for the test kit.
2. E.g. for Location tests, ensure Location is referenced in at least one Encounter linked to the patients whose IDs are used as input for the test kit.

**Comment by projkov** [comment]
@StephThaoOng Hello Steph

pre-requisites document is updated

https://github.com/hl7au/au-fhir-core-inferno/blob/master/docs/pre-requisites.md

**Comment by projkov** [comment]
@StephThaoOng Hello Steph
Can we close this issue?

**Comment by StephThaoOng** [comment]
@projkov 
For the pre-reqs that apply to all resources, can we just summarise it? Perhaps with the following wording:

> For all test groups/suites on Profiles:
> - Each _Must Support_ element is populated in at least one resource from the set of resources being tested. In other words, the set of resources being tested has coverage of the _Must Support_ elements; otherwise the test will be skipped.
> - Include at least one _Must Support_ reference within the test data set; otherwise the test will be skipped. 

> Additional pre-requisites for certain Profiles are as follows:

 Then list the extra pre-reqs for Location, Prac, PracRole etc. 

Also ensure that resource types are capitalised e.g. Practitioner resource and Organization resource, and _Must Support_ is formatted with capitals and italics to be consistent with the AU Core spec.

**Comment by projkov** [comment]
@StephThaoOng Hello Steph

What do you think about this version of the doc? It's a separate branch.
https://github.com/hl7au/au-fhir-core-inferno/blob/152-update-pre-requisites/docs/pre-requisites.md

**Comment by StephThaoOng** [comment]
> @StephThaoOng Hello Steph
> 
> What do you think about this version of the doc? It's a separate branch. https://github.com/hl7au/au-fhir-core-inferno/blob/152-update-pre-requisites/docs/pre-requisites.md

Hi @projkov thanks for this. How about this version: [Update pre-requisites and dependencies.md](https://github.com/hl7au/au-fhir-core-inferno/commit/c2953f2c8bcc3484f2f1e88bb6fb3943b701d19b) ?
Also if the test data pre-reqs for _Must Support_ elements are not met, I thought the test is skipped rather than failed?

**Comment by projkov** [comment]
> > @StephThaoOng Hello Steph
> > What do you think about this version of the doc? It's a separate branch. https://github.com/hl7au/au-fhir-core-inferno/blob/152-update-pre-requisites/docs/pre-requisites.md
> 
> Hi @projkov thanks for this. How about this version: [Update pre-requisites and dependencies.md](https://github.com/hl7au/au-fhir-core-inferno/commit/c2953f2c8bcc3484f2f1e88bb6fb3943b701d19b) ? Also if the test data pre-reqs for _Must Support_ elements are not met, I thought the test is skipped rather than failed?

Hello Steph

You are right, the test will be skipped not failed. 
I had used changes from your commit. Thanks!
