### ISSUE TITLE
Remove PractitionerRole multipleAND and multipleOR search by practitioner tests

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#154]
Remove PractitionerRole multipleAND and multipleOR search by practitioner tests. 
Support for these searches are not specified in AU Core 0.4.0-preview.

Version: V.0.0.9

**Comment by projkov** [comment]
@StephThaoOng Hello Steph

Are you sure that in version 0.4.0-preview, "multipleOr" and "multipleAnd" searches by the practitioner attribute for PractitionerRole do not exist?

It is a CapabilityStatement for the server [(Link)](https://fhirpath.me?url=https%3A%2F%2Fcorsproxy.io%2F%3Fhttps%3A%2F%2Fhl7.org.au%2Ffhir%2Fcore%2F0.4.0-preview%2FCapabilityStatement-au-core-responder.json&expression=CapabilityStatement.rest.resource.where(%0A%20%20%20%20type%3D'PractitionerRole').searchParam.where(name%3D'practitioner'))
I have selected a PractitionerRole and a searchParameter named "practitioner" for them. According to this data, the definition for this searchParameter is http://hl7.org.au/fhir/core/SearchParameter/au-core-practitionerrole-practitioner.

It is a SearchParameter resource with the URL http://hl7.org.au/fhir/core/SearchParameter/au-core-practitionerrole-practitioner. I have selected the extension related to the expectation for multipleOr. According to this data, it is MAY. [(Link)](https://fhirpath.me?url=https%3A%2F%2Fcorsproxy.io%2F%3Fhttps%3A%2F%2Fhl7.org.au%2Ffhir%2Fcore%2F0.4.0-preview%2FSearchParameter-au-core-practitionerrole-practitioner.json&expression=SearchParameter.multipleOr.extension.where(url%3D'http%3A%2F%2Fhl7.org%2Ffhir%2FStructureDefinition%2Fcapabilitystatement-expectation').valueCode)

The same applies to multipleAnd. [(Link)](https://fhirpath.me?url=https%3A%2F%2Fcorsproxy.io%2F%3Fhttps%3A%2F%2Fhl7.org.au%2Ffhir%2Fcore%2F0.4.0-preview%2FSearchParameter-au-core-practitionerrole-practitioner.json&expression=SearchParameter.multipleAnd.extension.where(url%3D'http%3A%2F%2Fhl7.org%2Ffhir%2FStructureDefinition%2Fcapabilitystatement-expectation').valueCode)

This means that we don't need to remove "multipleOr" and "multipleAnd" for the practitioner attribute in the PractitionerRole resource. Maybe I am missing something...

**Comment by StephThaoOng** [comment]
Thanks @projkov. Apologies, I/others were referring to the AU Core PractitionerRole Structure Definition and had overlooked to the SearchParameter artifact. Ticket will be closed.
