### ISSUE TITLE
Update the default server url

### ISSUE THREAD

**Issue by ir4y** [hl7au/au-fhir-core-inferno#16]
It should be https://sparked.npd.telstrahealth.com/smile/fhir/DEFAULT

Once it is done, please push changes to https://github.com/beda-software/au-fhir-core-inferno/ 
wait until CI is pass, then update image tag here https://github.com/hl7au/au-fhir-core-inferno/blob/master/infra/modules/au_fhir_inferno/input.tf#L17 and notify @KyleOps that new version should be deployed.

**Comment by projkov** [comment]
@KyleOps Hello!
Could you deploy a new version to the server?
