### ISSUE TITLE
Optimisation of Patient Resource Test 1.2.04: Include _count search parameter in conjunction with the gender search parameter for test.

### ISSUE THREAD

**Issue by JoshuaVazzolerMediRecords** [hl7au/au-fhir-core-inferno#164]
When performing a search with only the gender search parameter, it can return many patient resources depending on the size of the tenant. I recommend including _count  to improve the response time of this test. (E.g. _count=10).

**Comment by projkov** [comment]
@JoshuaVazzolerMediRecords Hello!

Thank you for reporting this issue. I'm happy to announce that this feature is available in the AU Core Test Kit v0.0.11.

Now, when you run the suite, you can use a setting called "Use _count search parameter for search tests (required)." By default, it's set to false. You can use values of 1, 10, 20, 50, and 100. This search parameter and the selected value will be used in all test suite search tests.

Please try the new functionality. I hope it will be helpful in your case! I look forward to your feedback. Have a good day!

**Comment by JoshuaVazzolerMediRecords** [comment]
Thanks @projkov, will give the new functionality a shot 👍 .

**Comment by projkov** [comment]
Hello @JoshuaVazzolerMediRecords 

I'm happy to announce that the ability to use the _count search parameter is now available by default, without any action required from the user. When you run the AU Core Test Kit, it will attempt to retrieve data with _count set to 1. If the response is successful, all subsequent search tests will use _count set to 10.

One important note:
Each test group (Patient, Condition, Encounter, etc.) will attempt to retrieve data with _count the first time. Therefore, in each test group, you will see the first search with _count set to 1, followed by the same request with _count set to 10.

I hope this enhancement improves your experience with our test kit! I would be happy to receive any feedback from you.
