### ISSUE TITLE
Inferno tests to validate create, update, delete interactions

### ISSUE THREAD

**Issue by projkov** [hl7au/au-fhir-core-inferno#185]
According to the specification, the responder MAY support these interactions with resources:

**create, update, delete, vread, patch, history-instance**

Do we need to start thinking about implementing inferno tests for these interactions?

**Comment by StephThaoOng** [comment]
As discussed with Sparked team on 5/8/24, these interactions are intended to be in scope for AU Core IG Release 2 so this ticket had been placed on hold.

**Comment by projkov** [comment]
I suggest to close this issue.
