### ISSUE TITLE
Generate AU Core v1.0.0-ballot test kit

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#187]
Hi @projkov 
AU Core version: 1.0.0-ballot is now available. Please generate Inferno AU Core v1.0.0-ballot test kit. 
Also remove v0.4.1-preview and v0.3.0-ballot from the list of test kits, if possible. 

fyi - plan is to reinstate Inferno AU Core v0.5.0-ci-build test kit after the Brisbane Connectathon as nothing normative will change in the ci-build until after the Connectathon.

**Comment by projkov** [comment]
Hello Steph! @StephThaoOng 

1.0.0-ballot is available
0.3.0-ballot, 0.4.1-ballot were removed

If all is good, then please close this issue. Thanks!
