### ISSUE TITLE
Update README with validation test suite information/instructions 

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#189]
Please update the README with validation test suite information/instructions. 
Please also consider whether the guide for the [FHIR validator](https://github.com/hl7au/au-fhir-core-inferno/blob/master/docs/validator_instructions.md) should be retained. If kept, we should point out the difference, if any.

**Comment by projkov** [comment]
@StephThaoOng Hello Steph!
What do you think about updated instructions?

https://github.com/hl7au/au-fhir-core-inferno/blob/master/docs/validator_instructions.md

If it's okay, then please close this issue. Thank you!

**Comment by StephThaoOng** [comment]
Hi @projkov thanks. Do you think it would be useful if we added some information about resources being validated with the Java validator using https://tx.dev.hl7.org.au/fhir as the terminology server? It might help users understand why they would choose to use this test kit for validation as opposed to https://inferno.healthit.gov/validator/
Otherwise the instructions look good. Thanks!

**Comment by projkov** [comment]
@StephThaoOng 

I like this idea! It will be informative for users. I’ll add it and then close the issue myself.

Thank you, Steph!
