### ISSUE TITLE
Running the server locally generates tests that return error 400 - Unknown search parameter &quot;specialty&quot

### ISSUE THREAD

**Issue by dattachandan** [hl7au/au-fhir-core-inferno#191]
Hi team

Thanks for this toolkit. 

When  I ran the container locally vs remote server, I see that the GET to the default FHIR server is different resulting in the server returning messages of parameters not supported.

This URL generated in the tests doesn't work(although should work) - https://fhir.hl7.org.au/aucore/fhir/DEFAULT/PractitionerRole?specialty=1268907002

This URL works - https://fhir.hl7.org.au/aucore/fhir/DEFAULT/PractitionerRole&specialty=1268907002

![image](https://github.com/user-attachments/assets/42e1509f-09f1-43f5-807e-38b1a833259c)

![image](https://github.com/user-attachments/assets/6a2ee6e9-e001-4ebb-8ab2-6180f65d984a)

![image](https://github.com/user-attachments/assets/b62449b1-60b4-4289-b6a3-2b87c33e4da8)

Not sure why the FHIR server is able to respond to only one request and I believe the test generator URLs are correct and should work in either case, can someone confirm? I tried with another FHIR server and it works fine

![image](https://github.com/user-attachments/assets/e9c180a0-d1b7-40eb-9ae5-1dd0674ab46b)

[AU Core v1.0.0-ballot Test Session.pdf](https://github.com/user-attachments/files/16565738/AU.Core.v1.0.0-ballot.Test.Session.pdf)

**Comment by StephThaoOng** [comment]
Hi @dattachandan @ir4y  Following up after the recent Connectathon, is this issue still open?

**Comment by dattachandan** [comment]
@StephThaoOng Thanks for following up. Can confirm that the reference server now worked on the test specified earlier in the post, will reopen if I see it fails since it has been redeployed since the Melbourne Core testing event number of times
![image](https://github.com/user-attachments/assets/ffa6fd80-b8f7-49e8-bdac-db9cf581a6cf)
