### ISSUE TITLE
Remove tests Server returns valid results for Patient multipleAnd / multiple Or search by indigenous-status / gender-identity

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#203]
Remove from the test kit:
1.2.13 Optional (MAY) Server returns valid results for Patient multipleOr search by indigenous-status
1.2.14 Optional (MAY) Server returns valid results for Patient multipleOr search by gender-identity
1.2.15 Optional (MAY) Server returns valid results for Patient multipleAnd search by indigenous-status
1.2.16 Optional (MAY) Server returns valid results for Patient multipleAnd search by gender-identity

AU Core has does not call out specifically MAY support for multipleAnd or multipleOr for these search parameters.

These should be removed from the suite of AU Core tests. 

Noting it is acknowledged that ALL search parameters allow (i.e. MAY) multipleAnd and multipleOr unless otherwise stated, and also acknowledge that this is likely pulled in due to how the test generator interprets the search parameters defined in from AU Base.

**Comment by projkov** [comment]
@StephThaoOng 

Hello Steph. Could you check the updates in production? If everything looks good, please close the issue.

**Comment by StephThaoOng** [comment]
Hi @projkov 
While these tests are no longer present from the web UI. I can see that these tests are still generated as seen in https://github.com/hl7au/au-fhir-core-inferno/tree/master/lib/au_core_test_kit/generated/v1.0.0-ci-build/patient 
Is this correct? 

Could you please check and link the commit that resolves this issue.

This will help ensure the tests are removed for an AU Core + test kit referenced in #208

**Comment by projkov** [comment]
> Hi @projkov While these tests are no longer present from the web UI. I can see that these tests are still generated as seen in https://github.com/hl7au/au-fhir-core-inferno/tree/master/lib/au_core_test_kit/generated/v1.0.0-ci-build/patient Is this correct?
> 
> Could you please check and link the commit that resolves this issue.
> 
> This will help ensure the tests are removed for an AU Core + test kit referenced in #208

@StephThaoOng  Hello Steph.
Now we have a delete step on CI, to prevent keeping old files
