### ISSUE TITLE
Remove MAY tests from AU Core Inferno

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#204]
While items in AU Core are marked MAY in the Implementation Guide to highlight their potential relevance to the use case there is not  strong need to support in testing.

Recommend removal. Or alternatively some sort of AU Core+ test kit that includes the SHALL, SHOULD, and MAY (noting ALL of the FHIR standard not explicitly prohibited is equivalent to MAY).

**Comment by StephThaoOng** [comment]
Sparked Tooling Meeting 10/9/24: Pavel to update config variable to exclude MAY tests.

**Comment by StephThaoOng** [comment]
Reviewed AU Core v1.0.0-ballot v.0.0.14 test kit - spot check of 8 test suites against AU Core 1.0.0-ballot. MAY tests have been excluded. 
This ticket can be closed. 
Upon further consideration, I think an AU Core+ test kit that includes the SHALL, SHOULD, and MAY tests would be beneficial for the implementer community for capability testing so I will raise a new issue.
