### ISSUE TITLE
Documentation should link to Sparked test data

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#206]
Either README or pre-requisites or some other page should link to the AU Core test data set that can be loaded and used in conjunction with inferno.

**Comment by projkov** [comment]
@StephThaoOng 

Hello Steph. Could you check the information about the test dataset here? https://github.com/hl7au/au-fhir-core-inferno/blob/master/docs/pre-requisites.md

If all is good, then please close this issue.

**Comment by StephThaoOng** [comment]
Hi @projkov can you please modify to the following text:

> An AU Core test data set that can be loaded and used in conjunction with Inferno is available at: https://github.com/hl7au/au-fhir-test-data
> This repo contains FHIR resources (JSON files) and Postman collections for testing purposes.
> The TestDataClient CLI tool can be used to upload FHIR resources to a target FHIR server. Refer to [au-fhir-test-data README.md#upload-data](https://github.com/hl7au/au-fhir-test-data/blob/master/README.md#upload-data) for more information.

**Comment by projkov** [comment]
Hello Steph @StephThaoOng 

The text was updated.
https://github.com/hl7au/au-fhir-core-inferno/blob/master/docs/pre-requisites.md
