### ISSUE TITLE
Add links to the footer

### ISSUE THREAD

**Issue by projkov** [hl7au/au-fhir-core-inferno#213]
I found a useful property in the Inferno suite called "links." It allows us to add any links to the footer with custom titles. Should we consider adding this feature? I think it could be beneficial for users.

Create an issue: link to all issues on GitHub or directly to the issue creation form;
Source code: link to the GitHub repository;
AU Core Implementation Guide: link to the IG.

Do we need to add this to the project? It's a small task.

![Screenshot from 2024-09-26 16-23-00](https://github.com/user-attachments/assets/f3eb3ae1-a612-48b1-8486-1a8e90a2e1d0)

**Comment by projkov** [comment]
@StephThaoOng Hello Steph
You can check the update on production.

**Comment by StephThaoOng** [comment]
Looks good and useful. Thanks Pavel
