### ISSUE TITLE
Check how we can create a static pages

### ISSUE THREAD

**Issue by ir4y** [hl7au/au-fhir-core-inferno#3]
We need a landing page like so https://inferno.healthit.gov/test-kits/us-core/ but for AU Core to share info about the test kit and validation piloting.
Maybe static pages should be a part of https://github.com/hl7au/au-fhir-inferno

**Comment by projkov** [comment]
Discussion:

https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Question.20regarding.20Web.20UI.20for.20multiple.20test.20kits

**Comment by projkov** [comment]
I have tested the implementation of the "Test Kit Templates" service that were released a few days ago. It looks like we can use it without any trouble.

Link to the repository: https://github.com/inferno-framework/inferno-platform-template

What we can do with it:
1. Manage any Test Kits via Ruby gems, add meta information about these kits, and run them from this service.
2. Edit the header.
3. Edit the footer.
4. Manage news.
5. Manage the index page content.
6. Manage the events list.
7. Manage the about page.

**Comment by jgsuess** [comment]
@projkov @ir4y @mjosborne1 @brettesler-ext Where can I find the source code for the SSG for https://inferno.healthit.gov/ ? That would be the thing I need to clone, correct?

**Comment by StephThaoOng** [comment]
> @projkov @ir4y @mjosborne1 @brettesler-ext Where can I find the source code for the SSG for https://inferno.healthit.gov/ ? That would be the thing I need to clone, correct?

Hi @jgsuess I think the source code can be found in https://github.com/inferno-framework/inferno-platform-template 
Can we assign this ticket back to Pavel or would you like to continue? Sparked tooling team should have capacity now to pick this up. 
Thanks :)

**Comment by jgsuess** [comment]
Please assign this ticket back to Pavel. Thanks!

**Comment by StephThaoOng** [comment]
> I made a list of tasks that we should complete if we want to run this template for our purposes:
> 
> 1. Decide which content pages we want to keep and manage (events, news, about, index page).
> 2. Decide who will be responsible for these pages and how they will manage them.
> 3. Prepare initial content for the first run.
> 4. Prepare the AU Core Test Kit as a Ruby Gem.
> 5. Set up CI/CD.

Hi @projkov, list of tasks looks good.
Re: 
> 1. Decide which content pages we want to keep and manage (events, news, about, index page).
- Replicate/retain all content pages (about, index of test kits, news & updates, events). Note for events we will likely only provide info/link that redirects to upcoming AU FHIR Tooling and Infrastructure work group meetings (which are soon to be setup). 

> 2. Decide who will be responsible for these pages and how they will manage them.
- Sparked Tooling team responsible for maintaining these pages. Details to be worked out internally.
