### ISSUE TITLE
Use http://tx.dev.hl7.org.au/ terminology server

### ISSUE THREAD

**Issue by ir4y** [hl7au/au-fhir-core-inferno#35]
There are three versions of terminology servers:
 - http://tx.dev.hl7.org.au/
 - http://tx.test.hl7.org.au/ -> http://tx.hl7.org.au/

We need to define in which scenario what server should be used:
- Testsure for the current development version of the specification https://build.fhir.org/ig/hl7au/au-fhir-core/ that in the development  https://github.com/hl7au/au-fhir-core
- Testsure for the latest release 0.3.0-ballot
- Testsure for previous releases like 0.2.2-preview,0.2.1-preview, 0.3.0-ballot once v0.4.0-preview will be release.

- FHIR validator for the current development version of the specification https://build.fhir.org/ig/hl7au/au-fhir-core/ that in the development  https://github.com/hl7au/au-fhir-core
- FHIR validator for the latest release 0.3.0-ballot
- FHIR validator for previous releases like 0.2.2-preview,0.2.1-preview, 0.3.0-ballot once v0.4.0-preview will be release.

Also, now you have to manually choose what profile should be used for the validation, and there is no option to choose a specific version of the. profile. Should we provide a better UX for FHIR validator?

**Comment by ir4y** [comment]
http://tx.hl7.org.au/ will be used only for STU releases, for all dev versions we are going to use http://tx.dev.hl7.org.au/

**Comment by projkov** [comment]
Changing the terminology server raised problems in a few test groups:

    1.6 Observation Pathology Result Tests
    1.11 Observation Diagnostic Result Tests

I'll try to fix it tomorrow.
