### ISSUE TITLE
Bug in AU Core Patient identifier test - allows code only and shouldn't

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#44]
This get `https://sparked.npd.telstrahealth.com/smile/fhir/DEFAULT/Patient?identifier=6951449677` is not OK. AU Core mandates code and system for Patient identifier search.

This is in AU Core v0.3.0-ballot

**Comment by projkov** [comment]
This problem was fixed.
Issue can be closed.
