### ISSUE TITLE
Add optional search for chained patient.identifier parameter

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#46]
Servers SHOULD provide support using the search parameter patient.identifier. Add this to:
1. all Observation tests.
2. AllergyIntolerance
3. Condition
4. Encounter
5. Immunization
6. MedicationRequest
7. Procedure

**Comment by projkov** [comment]
Hello @dt-r 

I have checked the CapabilityStatement server JSON file, which is used by the generator to create search tests. There is no 'patient.identifier' item in the searchParameters attribute. Only the 'patient' item exists. 

For example, for the Observation resource

```
CapabilityStatement.rest.resource.where(type='Observation').searchParam
```

Response will be

```
[
    {
        "extension": [
            {
                "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
                "valueCode": "MAY"
            }
        ],
        "name": "category",
        "definition": "http://hl7.org/fhir/SearchParameter/Observation-category",
        "type": "token",
        "documentation": "The client **SHALL** provide at least a code value and **MAY** provide both the system and code values.\n\nThe server **SHALL** support both."
    },
    {
        "extension": [
            {
                "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
                "valueCode": "MAY"
            }
        ],
        "name": "code",
        "definition": "http://hl7.org/fhir/SearchParameter/clinical-code",
        "type": "token",
        "documentation": "The client **SHALL** provide at least a code value and **MAY** provide both the system and code values.\n\nThe server **SHALL** support both."
    },
    {
        "extension": [
            {
                "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
                "valueCode": "MAY"
            }
        ],
        "name": "date",
        "definition": "http://hl7.org/fhir/SearchParameter/clinical-date",
        "type": "date",
        "documentation": "A client **SHALL** provide a value precise to the *second + time offset*.\n\nA server **SHALL** support a value precise to the *second + time offset*. \n\nThe client **SHALL** support these search comparators `gt`, `lt`, `ge`, `le`.\n\nThe server **SHALL** support these search comparators `gt`, `lt`, `ge`, `le`."
    },
    {
        "extension": [
            {
                "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
                "valueCode": "MAY"
            }
        ],
        "name": "status",
        "definition": "http://hl7.org/fhir/SearchParameter/Observation-status",
        "type": "token",
        "documentation": "The client **SHALL** provide at least a code value and **MAY** provide both the system and code values.\n\nThe server **SHALL** support both."
    },
    {
        "extension": [
            {
                "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
                "valueCode": "SHALL"
            }
        ],
        "name": "patient",
        "definition": "http://hl7.org.au/fhir/core/SearchParameter/au-core-clinical-patient",
        "type": "reference",
        "documentation": "The client **SHALL** provide at least an id value and **MAY** provide both the Type and id values.\n\nThe server **SHALL** support both.\n\nThe client **SHOULD** support chained search patient.identifier using IHI, Medicare Number, and DVA Number identifiers as defined in the AU Core Patient profile.\n\nThe server **SHOULD** support chained search patient.identifier using IHI, Medicare Number, and DVA Number identifiers as defined in the AU Core Patient profile."
    }
]
```

The information about 'patient.identifier' exists in the documentation attribute for the patient search parameter. I'm not sure, but there should be another way to describe 'patient.identifier' as a search parameter. Correct me if I'm wrong.

**Comment by dt-r** [comment]
The structural way of declaring the patient.identifier is supported is to profile the patient SearchParmeter in AU Core, and update the patient parameter reference to be the AU Core definition instead of the FHIR definition. There are no inline entry in the Capability Statement for chained elements of a particular parameter... it is through reference to the definition of the parameter. This is already done for this particular parameter, but not all of them.

You are welcome to suggest that AU Core adds in more profiled SearchParameters to the IG via adding a JIRA change request. I don't think it will make it into R1. I am on the fence at which release of AU Core we may introduce this to. It is rare for an IG to do anything more than document in narrative the use of chained params or multipleOr etc. because almost no-one is using those artefacts. I'd be interested to see how many people would want to use them and how.

**Comment by projkov** [comment]
- [ ] all Observation tests
- [ ] AllergyIntolerance
- [ ] Condition
- [ ] Encounter
- [ ] Immunization
- [ ] MedicationRequest
- [ ] Procedure

**Comment by StephThaoOng** [comment]
Hi @projkov on review of Immunization tests 1.16.10 to 1.16.13, the resources for the patient ids provided on the Sparked FHIR server definitely have the values to perform the search. So the returned response seems incorrect.
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/36804832/5c123c7c-3c0c-4713-b9df-2f3a6d16c65a)

**Comment by projkov** [comment]
Hello @StephThaoOng 

I think it should work. Could you run it one more time? Also, this test could be dependent, so it can't run without other tests.

**Comment by StephThaoOng** [comment]
Hi @projkov 

- Tested again on Procedure and test _1.18.10 Server returns valid results for Procedure search by patient (chained parameters)_ still doesn't work even though the patient=italia-sofia resource has that passport identifier.

- Tested again on MedicationRequest and search by patient.identifier doesn't work. Patient 'dan-harry' does have a DVA so neither test 1.17.12 or 1.17.15 should have failed.

**Comment by projkov** [comment]
@StephThaoOng Hello Steph!

I will check it tomorrow morning, but it should be fixed. In general, the problem lies with the patients. All cases with failed tests related to the identifier that I saw have a similar issue: demo patients whose IDs are used in the input are not referenced in the target resource.

Here's an example:
1. **Procedure tests:** If you run this test with the default demo patients, you will get a failed IHI test. This is because there are only three Procedure resources in the system. These resources are referenced to Patient/bennelong-anne, Patient/dan-harry, and Patient/wang-li. **These three patients definitely don't have an IHI identifier.**
2. **MedicationRequest tests:** With the default patients, the DVA test will fail. This is because there are only four MedicationRequest resources on the server. These resources are referenced to Patient/bennelong-anne, Patient/wang-li, and Patient/hayes-arianne. **These three patients definitely don't have a DVA identifier.**

Could you review it? Thanks!

**Comment by StephThaoOng** [comment]
@projkov thanks! I understand it more fully now. I will add more clinical resources to the default demo patients today.
