### ISSUE TITLE
Tests that are incorrectly marked as Optional

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#47]
The following tests are NOT Optional as they are mandatory search parameter combinations in AU Core. Please fix so not optional:
* Observation search by patient + category + date e.g. 1.3.08, 1.4.08, 1.5.08, etc
* 1.19.05 Optional Server returns valid results for Procedure search by patient + date
* 1.15.09 Optional Server returns valid results for Encounter search by date + patient

**Comment by projkov** [comment]
**To fix:**

[ ] Observation search by patient + category + date e.g. 1.3.08, 1.4.08, 1.5.08, etc
[ ] 1.19.05 Optional Server returns valid results for Procedure search by patient + date
[ ] 1.15.09 Optional Server returns valid results for Encounter search by date + patient

**Comment by projkov** [comment]
Hello Steph @StephThaoOng 

Looks like this issue can be closed.
