### ISSUE TITLE
Missing comparators gt,lt,ge,le in tests for date  & onset-date & authoredon

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#48]
AU Core requires that the following search parameters or search parameter combinations SHALL support the comparators gt,lt,ge,le
- 1.3.08 Optional Server returns valid results for Observation search by patient + category + date and other Observation profile tests up to 1.12.08 Optional Server returns valid results for Observation search by patient + category + date
- 1.3.10 Optional Server returns valid results for Observation search by patient + code + date and other Observation profile tests up to 1.12.10 Optional Server returns valid results for Observation search by patient + category + date
- 1.14.05 Optional Server returns valid results for Condition search by onset-date
- 1.14.10 Optional Server returns valid results for Condition search by patient + onset-date
- 1.15.03 Optional Server returns valid results for Encounter search by date
- 1.15.09 Optional Server returns valid results for Encounter search by date + patient
- 1.16.02 Optional Server returns valid results for Immunization search by date
- 1.16.06 Optional Server returns valid results for Immunization search by patient + date
- 1.17.05 Optional Server returns valid results for MedicationRequest search by authoredon
- 1.17.10 Server returns valid results for MedicationRequest search by patient + intent + authoredon

Please add tests for gt, lt, ge, and le to those tests.

**Comment by projkov** [comment]
Changes to fix this issue were merged to the master branch.
