### ISSUE TITLE
Observation date tests missing required AU Core precision

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#49]
The Observation date test provides a value precise to the day, it does not have the required precision from AU Core. See AU Core excerpt below:
A client SHALL provide a value precise to the second + time offset. A server SHALL support a value precise to the second + time offset.

This applies to all Observation tests. Please fix.

**Comment by projkov** [comment]
Hello @dt-r

Changes related to this ticket should be available on the server. Could you retest it?
If everything is okay then please close the ticket.
