### ISSUE TITLE
Make choice of terminology sever configurable 

### ISSUE THREAD

**Issue by ir4y** [hl7au/au-fhir-core-inferno#5]
For dev installation, we are going to use [tx.test.hl7.org.au](http://tx.test.hl7.org.au/)
While production testing will interact with [tx.fhir.org](http://tx.fhir.org/)

There should be a way to switch easily between terminology servers, and tx.test.hl7.org.au should be used by default.

**Comment by projkov** [comment]
@ir4y What are your thoughts on this approach? If it meets your approval, please proceed to close the issue.
https://github.com/hl7au/au-fhir-core-inferno/commit/9286646f50950b2e74646c9dae1af9dfe21baa59
