### ISSUE TITLE
Condition onset-date tests missing required AU Core precision

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#60]
The onset-date test provides a value precise to the day, it does not have the required precision from AU Core. See AU Core excerpt below:
A client SHALL provide a value precise to the second + time offset. A server SHALL support a value precise to the second + time offset.

Please fix.

**Comment by projkov** [comment]
Hello @dt-r ,

I'm pleased to announce that the changes related to this ticket are now available in version 0.0.6, which has already been deployed to the server.

Please re-test the changes. If everything is okay, you may close this ticket. If you encounter any issues or do not observe the changes related to this ticket, please provide details here.

Thank you.

https://inferno.hl7.org.au
