### ISSUE TITLE
Add optional multipleAnd tests for date & onset-date & authoredon

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#62]
AU Core says SHOULD support multipleAnd for date, onset-date, and authoredOn parameters. Please add a multipleAnd test to:
* 1.3.08 Optional Server returns valid results for Observation search by patient + category + date and other Observation profile tests up to 1.12.08 Optional Server returns valid results for Observation search by patient + category + date
* 1.3.10 Optional Server returns valid results for Observation search by patient + code + date and other Observation profile tests up to 1.12.10 Optional Server returns valid results for Observation search by patient + category + date
* 1.14.05 Optional Server returns valid results for Condition search by onset-date
* 1.14.10 Optional Server returns valid results for Condition search by patient + onset-date
* 1.15.03 Optional Server returns valid results for Encounter search by date
* 1.15.09 Optional Server returns valid results for Encounter search by date + patient
* 1.16.02 Optional Server returns valid results for Immunization search by date
* 1.16.06 Optional Server returns valid results for Immunization search by patient + date
* 1.17.05 Optional Server returns valid results for MedicationRequest search by authoredon
* 1.17.10 Server returns valid results for MedicationRequest search by patient + intent + authoredon

**Comment by projkov** [comment]
- [ ] 1.3.08 Optional Server returns valid results for Observation search by patient + category + date and other Observation profile tests up to 1.12.08 Optional Server returns valid results for Observation search by patient + category + date
- [ ] 1.3.10 Optional Server returns valid results for Observation search by patient + code + date and other Observation profile tests up to - [ ] 1.12.10 Optional Server returns valid results for Observation search by patient + category + date
- [ ] 1.14.05 Optional Server returns valid results for Condition search by onset-date
- [ ] 1.14.10 Optional Server returns valid results for Condition search by patient + onset-date
- [ ] 1.15.03 Optional Server returns valid results for Encounter search by date
- [ ] 1.15.09 Optional Server returns valid results for Encounter search by date + patient
- [ ] 1.16.02 Optional Server returns valid results for Immunization search by date
- [ ] 1.16.06 Optional Server returns valid results for Immunization search by patient + date
- [ ] 1.17.05 Optional Server returns valid results for MedicationRequest search by authoredon
- [ ] 1.17.10 Server returns valid results for MedicationRequest search by patient + intent + authoredon

**Comment by projkov** [comment]
The fix for this issue will be merged. 
Now, multipleOr and multipleAnd requests are independent tests. It's simpler to read and understand.

https://github.com/hl7au/au-fhir-core-inferno/pull/75

**Comment by projkov** [comment]
Hello @dt-r

Changes related to this ticket should be available on the server. Could you retest it?
If everything is okay then please close the ticket.

**Comment by StephThaoOng** [comment]
thanks @projkov 

multipleAND tests implemented separately/on the single search parameter.
Moved to "on-hold" status; to be discussed at Sparked tooling meeting 24/6 to verify if issue can be closed.

**Comment by StephThaoOng** [comment]
> thanks [@projkov](https://github.com/projkov)
> 
> multipleAND tests implemented separately/on the single search parameter. Moved to "on-hold" status; to be discussed at Sparked tooling meeting 24/6 to verify if issue can be closed.

24/6 Infra&Tooling meeting - agreed that for AU Core capability testing, it is reasonable to implement tests for "multipleOr" search and "multipleAnd" search separately.
