### ISSUE TITLE
Tests should fail if terminology with a 'required' binding cannot be validated.

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#72]
If terminology with a 'required' binding cannot be validated, the test should fail. Currently, the tests seem to pass with a warning. 

Example: Test 1.13.06 currently passes with warnings despite required terminology bindings
![InfernoIssue02](https://github.com/hl7au/au-fhir-core-inferno/assets/36804832/55f4faa5-e18d-49e0-ac08-60bd2de1a3a2)

**Comment by StephThaoOng** [comment]
Closing this issue as it is duplicate of [issue #110 ](https://github.com/hl7au/au-fhir-core-inferno/issues/110).

**Comment by StephThaoOng** [comment]
6/6 Agreed that tests should fail if terminology binding is required and code/value set is not found.

**Comment by projkov** [comment]
@StephThaoOng Hello, Steph.
Could you provide more details related to this issue?

I had a try to run test-kit with default patient IDs. I got a list of warnings (warnings related to the narrative are removed from this list)

1. AllergyIntolerance/dust: AllergyIntolerance.code: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2 not found
2. AllergyIntolerance/lactose: AllergyIntolerance.reaction[0].substance: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/adverse-reaction-agent-1 not found
3. AllergyIntolerance/lactose: AllergyIntolerance.reaction[0].manifestation[0]: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1 not found
4. AllergyIntolerance/lactose: AllergyIntolerance.reaction[0].manifestation[1]: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1 not found
5. AllergyIntolerance/lactose: AllergyIntolerance.reaction[0].manifestation[2]: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1 not found
6. AllergyIntolerance/lactose: AllergyIntolerance.code: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2 not found
7. AllergyIntolerance/nkda: AllergyIntolerance.code: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2 not found
8. AllergyIntolerance/egg: AllergyIntolerance.reaction[0].substance: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/adverse-reaction-agent-1 not found
9. AllergyIntolerance/egg: AllergyIntolerance.reaction[0].manifestation[0]: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1 not found
10. AllergyIntolerance/egg: AllergyIntolerance.code: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2 not found
11. AllergyIntolerance/penicillin: AllergyIntolerance.reaction[0].substance: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/adverse-reaction-agent-1 not found
12. AllergyIntolerance/penicillin: AllergyIntolerance.reaction[0].manifestation[0]: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1 not found
13. AllergyIntolerance/penicillin: AllergyIntolerance.code: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2 not found
14. AllergyIntolerance/wasp: AllergyIntolerance.reaction[0].substance: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/adverse-reaction-agent-1 not found
15. AllergyIntolerance/wasp: AllergyIntolerance.reaction[0].manifestation[0]: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1 not found
16. AllergyIntolerance/wasp: AllergyIntolerance.reaction[0].manifestation[1]: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1 not found
17. AllergyIntolerance/wasp: AllergyIntolerance.reaction[0].manifestation[2]: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/clinical-finding-1 not found
18. AllergyIntolerance/wasp: AllergyIntolerance.code: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2 not found
19. AllergyIntolerance/noneknown: AllergyIntolerance.code: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2 not found
20. AllergyIntolerance/noneknown-tc-1.13: AllergyIntolerance.code: ValueSet https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2 not found

According to the StructureDefinition file, AllergyIntollerance has these elements with required binding:

1. AllergyIntolerance.clinicalStatus
2. AllergyIntolerance.verificationStatus
3. AllergyIntolerance.type
4. AllergyIntolerance.category
5. AllergyIntolerance.criticality
6. AllergyIntolerance.reaction.severity

Maybe I missed something, but it looks like everything is good. I mean, it's okay if the error does not exist. Or maybe I don't understand the problem correctly.

**Comment by StephThaoOng** [comment]
@projkov - apologies, our mistake (I was reporting the issue on behalf of someone). As you've noted, the terminology bindings are preferred, not required. 
I'll close this issue.

A separate issue is the value sets that cannot be found.
For the value sets reported above as "not found", checking via Postman found these value sets on https://tx.dev.hl7.org.au/fhir e.g. for the first warning on AllergyIntolerance/dust:
`http://tx.dev.hl7.org.au/fhir/ValueSet/$validate-code?url=https://healthterminologies.gov.au/fhir/ValueSet/indicator-hypersensitivity-intolerance-to-substance-2&system=http://snomed.info/sct&code=33008008
` successfully validated.
I also checked using the FHIR CLI validator on [allergy0.json](https://github.com/user-attachments/files/15944329/allergy0.json):
`java -jar validator_cli.jar -version 4.0 -ig hl7.fhir.au.core#0.4.0-preview -tx https://tx.dev.hl7.org.au/fhir allergy0.json` and it did not reproduce the same errors.
To be discussed and fixed with @mjosborne1
