### ISSUE TITLE
Add a Practitioner.identifier search test for HPI-I

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-core-inferno#77]
SHOULD optional search test
eg.

  ?identifier=http://ns.electronichealth.net.au/id/hi/hpii/1.0|8003619900015717

and

?identifier=8003619900015717

**Comment by projkov** [comment]
Hello @brettesler-ext 

Changes related to this ticket should be available on the server. Could you retest it?
If everything is okay then please close the ticket.
