### ISSUE TITLE
Recent Practitioner profile approved MS removals

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-core-inferno#78]
removed MustSupport on qualification, address, communication, telecom - modify checks

Approved changes from https://confluence.hl7.org/display/HAFWG/AU+Core+R1+Ballot+for+Comment+Reconciliation+Triage
[FHIR-44587](https://jira.hl7.org/browse/FHIR-44587) qualification
[FHIR-43860](https://jira.hl7.org/browse/FHIR-43860) address & telecom
[FHIR-44588](https://jira.hl7.org/browse/FHIR-44588) communication

**Comment by projkov** [comment]
Hello Brett!

Thank you for reporting the issue. MS attributes are retrieved from the IG automatically by the test generator.

I checked MS attributes for version 0.4.0 in the generated tests, and they look good (MS is not enabled for these attributes).

**Comment by brettesler-ext** [comment]
Thanks Pavel
