### ISSUE TITLE
Recent Condition profile approved MS removals

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-core-inferno#79]
Approved changes remove MustSupport on Condition - asserter, recorder, encounter

From https://confluence.hl7.org/display/HAFWG/AU+Core+R1+Ballot+for+Comment+Reconciliation+Triage approvals:
[FHIR-45127](https://jira.hl7.org/browse/FHIR-45127) asserter
[FHIR-45019](https://jira.hl7.org/browse/FHIR-45019) recorder
[FHIR-45189](https://jira.hl7.org/browse/FHIR-45189) encounter

**Comment by projkov** [comment]
Hello Brett.
Thank you for reporting the issue. MS attributes are retrieved from the IG automatically by the test generator.
I checked MS attributes for version 0.4.0 in the generated tests, and they look good (MS is not enabled for these attributes).

**Comment by brettesler-ext** [comment]
Thanks Pavel
