### ISSUE TITLE
AU Core AllergyIntolerance - add tests for search using the using IHI, Medicare Number, and DVA Number identifiers.

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#80]
Enhancements to achieve full test coverage of search using patient.identifier parameter (of type reference.token) i.e. add tests for search using IHI, Medicare Number, and DVA Number identifiers as defined in the AU Core Patient profile.

**Comment by StephThaoOng** [comment]
Ran the tests using AU Core v0.4.0-ci-build but the results are not as expected. 
Response is 
> I don't have values to perform search
which is not true as the test dataset definitely have identifiers that enable running these tests.

**Comment by projkov** [comment]
@StephThaoOng Could you provide information about what ID of the patient you used to get this problem? When I try to use it everything looks good. 

NOTE: There is no IHI identifier in default patients for search. Maybe we should update the default patient ids for search...

If all good, please close this ticket

**Comment by StephThaoOng** [comment]
Hi @projkov 
Search by patient (Medicare) (chained parameters) still doesn't work for me. See below
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/36804832/cd72120d-2879-48cc-8283-e6499bb4932e)

Acknowledge that there is no IHI identifier in default patients for search. This is ok. Once search by patient Medicare identifier fixed, this tix can be closed.
