### ISSUE TITLE
Capability Statement SMART on FHIR is not MUST

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core-inferno#91]
SMART on FHIR is not MUST – it is a SHOULD
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/8864e923-a842-47dd-b4ce-c35ba7c1e8e0)

**Comment by heathfrankel** [comment]
29/5 Agreed to remove the sentence referring to SMART on FHIR endpoints being required to be advised.

**Comment by projkov** [comment]
Hello @heathfrankel  ,

I'm pleased to announce that the changes related to this ticket are now available in version 0.0.6, which has already been deployed to the server.

Please re-test the changes. If everything is okay, you may close this ticket. If you encounter any issues or do not observe the changes related to this ticket, please provide details here.

Thank you.

https://inferno.hl7.org.au/
