### ISSUE TITLE
Capability Statement Patient resource and only one additional resource profile

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core-inferno#92]
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/59a55435-0061-4c46-bbd1-de3985ff5d5e)

> AU Core implementation guide … and only one additional resource profile …

This suggested only one other resource, where as the Capability Statement indicates “at least one additional resource profile from the list of AU Core Profiles”.

Suggest using language from the 0.4.0 IG (must-support-obligation branch) Conformance General Requirements page. E.g. 
> The AU Core Responder SHALL:
> 1. Support the AU Core Patient resource profile.
> 2. Support at least one additional resource profile from the list of AU Core Profiles.

Update reference to “AU Core implementation guide” as “AU Core Responder Capability Statement”

Update “AU Core Server” as “AU Core Responder”

**Comment by heathfrankel** [comment]
29/5: Agreed changes

1. Change "The AU Core Implementation Guide requires that the Patient resource and only one additional resource profile from the AU Core Profiles" is changes to "The AU Core Responder Capability Statement requires that the Patient resource and **at least** one additional resource profile from the AU Core profiles"
2. Change  "The features described in the Capability Statement must be consistent with the required capabilities of a AU Core server" to "The features described in the Capability Statement must be consistent with the required capabilities of a AU Core **Responder**"

**Comment by projkov** [comment]
The fix is available on production in version 0.0.12. The issue can be closed.
