### ISSUE TITLE
Capability Statement test methodology indicates that testing verifies is secure using cryptographic protocol

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core-inferno#93]
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/9cf90334-2c8d-4d3d-bd43-5ee72cddea08)

AU Core does not require any particular Cryptographic protocol – only SHOULD conform to FHIR Communication Security requirements that makes a recommendation (SHOULD).

The following tests show as errors, but should only be warnings at most
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/59899b83-fed9-41ed-b141-38099d9c1f57)

A number of errors raised regarding the CapabilityStatement content, appears to be concerned with some security extensions which I don't think we have.
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/afea89de-4d0d-420b-a6f5-78adf788d9dd)

**Comment by heathfrankel** [comment]
29/5 Agreed to await decision from TDG on whether TLS 1.2 and above will be mandated in R1 or not before removing

**Comment by ir4y** [comment]
It was a while since this conversation.
R1 is out and contain some guidance about encryption.
@projkov could you please check the current state of the specification and check if it is aligned with tests.

**Comment by projkov** [comment]
> It was a while since this conversation. R1 is out and contain some guidance about encryption. @projkov could you please check the current state of the specification and check if it is aligned with tests.

https://build.fhir.org/ig/hl7au/au-fhir-core/security.html

According to the specification:

```
Systems SHALL use TLS version 1.2 or higher for data exchange.
```

This means that we need to keep test 1.1.01 as SHALL
