### ISSUE TITLE
Capability Statement warnings related to missing language CodeSystem 

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core-inferno#94]
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/c882cd27-a73b-431f-85d3-b0c1e03835ab)
Warning messages about a BCP:13 codesystem not found for the format element. 

There is no codesystem specified in the resource (it is only a code, no system), so it must be an issue in inferno looking to validate the code from this code system using a terminology server that doesn't have this codesystem.

I would expect the tx.dev server to have this configured.

**Comment by heathfrankel** [comment]
29/5 Retested and don't think this issue exists any more

HF to double check

**Comment by heathfrankel** [comment]
Although the warning no longer exists, there are now multiple errors that refer to unknown codes
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/1833d16d-63c6-48da-8f3d-7c19c81e2fa4)

These are related to the format element values in the capability statement.
So perhaps the urn:itef:bcp:13 code system now exists in tx.dev, but doesn't contain these values?

![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/339d0651-e42d-47d3-afe3-f7c0e26d72cb)

@brettesler-ext has suggest that Michael Osborne can investigate/resolve this issue.

**Comment by heathfrankel** [comment]
I think that some of these format codes are actuall invalid mimetypes, including
I would actually suggest that some of the others in this instance are actually invalid mime types, such as 
    "xml",
    "json",
    "ttl",
    "html/json",
    "html/xml",
    "html/turtle"

However, I have asked Michael Osbone to add application/fhir+json and application/fhir+xml to
urn:ietf:bcp:13 code system on tx.dev and ensure they are included in
http://hl7.org/fhir/ValueSet/mimetypes valueset

**Comment by mjosborne1** [comment]
tx.dev : http://hl7.org/fhir/ValueSet/mimetypes contain the fhir mimetypes now.
Try this in Postman to verify : https://tx.dev.hl7.org.au/fhir/ValueSet/$expand?url=http://hl7.org/fhir/ValueSet/mimetypes&filter=fhir

**Comment by StephThaoOng** [comment]
This is a FHIR validator issue. 
@mjosborne1 investigating. 
Will update here when resolved and ready for re-testing.

**Comment by projkov** [comment]
Hello everyone! @StephThaoOng @heathfrankel @mjosborne1

What is the status of this issue? Now we have a validator wrapper with validator v6.3.11
You can run CapabilityStatement tests and check the results. Did the update of the validator help?

**Comment by StephThaoOng** [comment]
> Hello everyone! @StephThaoOng @heathfrankel @mjosborne1
> 
> What is the status of this issue? Now we have a validator wrapper with validator v6.3.11 You can run CapabilityStatement tests and check the results. Did the update of the validator help?

Hi @projkov 
Currently, failure of test _1.1.02 FHIR Server supports the conformance interaction_ relates to mime type and security extension errors on the AU Core node Capability Statement. 
This issue has been raised with Telstra Health to be addressed with Smile CDR. 
Hence, we can close this ticket as no further action required for the Inferno AU Core test kit.
