### ISSUE TITLE
Capability Statement server version passed when HTML page returned

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core-inferno#95]
Using the MediRecords server https://fhir.test.medirecords.com/fhir/metadata, a HTML page is returned instead of a CapabilityStatement resource.

However, the test for using JSON passed even though the HTML page was returned and wouldn't be able to find a the CapabilityStatement element indicating that JSON is supported.

![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/22b8c553-ea54-4edf-a5a9-8d4a7d8a3abc)

**Comment by heathfrankel** [comment]
Agree that this should not pass

**Comment by projkov** [comment]
Hello @heathfrankel  ,

I'm pleased to announce that the changes related to this ticket are now available in version 0.0.6, which has already been deployed to the server.

Please re-test the changes. If everything is okay, you may close this ticket. If you encounter any issues or do not observe the changes related to this ticket, please provide details here.

Thank you.

https://inferno.hl7.org.au/

**Comment by StephThaoOng** [comment]
Retested using the MediRecords test server and the JSON support test fails as expected.
