### ISSUE TITLE
Capability Statement test references to US Core and USCDI

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core-inferno#96]
Reference to US Core
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/c6dbcb38-90ed-4378-9f60-c0e71782a676)

Reference to USCDI
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/efcf8907-4edf-4d86-b571-bfd2a1f78329)

In fact, there is no requirement to support all AUCDI resources, remove this altogether.

**Comment by heathfrankel** [comment]
Agreed changes
1. Change "US Core interactions" to "**AU Core Responder** interactions"
2. Remove sentence "In order to support USCDI, servers must support all USCDI resources"

**Comment by projkov** [comment]
Hello @heathfrankel ,

I'm pleased to announce that the changes related to this ticket are now available in version 0.0.6, which has already been deployed to the server.

Please re-test the changes. If everything is okay, you may close this ticket. If you encounter any issues or do not observe the changes related to this ticket, please provide details here.

Thank you.

https://inferno.hl7.org.au/
