### ISSUE TITLE
Capability Statement missing SHOULD support XML test

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core-inferno#97]
AU Core Responder Capability Statement indicates SHOULD support XML, no test for this case.

**Comment by heathfrankel** [comment]
Agree to add a optional test for capability statement support of XML

**Comment by projkov** [comment]
Hello @heathfrankel  ,

I'm pleased to announce that the changes related to this ticket are now available in version 0.0.6, which has already been deployed to the server.

Please re-test the changes. If everything is okay, you may close this ticket. If you encounter any issues or do not observe the changes related to this ticket, please provide details here.

Thank you.

https://inferno.hl7.org.au/
