### ISSUE TITLE
Capability Statement may requirement test cases

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core-inferno#98]
Although I think we should provide tests for SHOULD compliance (e.g. support for XML), I wonder if we also include MAY compliance for the following in order to provide a full level of capability, not just mandatory and recommended capabilities.
For example:
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/ebdb2de9-4641-4de4-9529-6c3d068b6380)

**Comment by heathfrankel** [comment]
Agreed that adding tests for MAY conformance requirements are a low priority, they can be implemented when there is spare capacity.

**Comment by Sudo-JHare** [comment]
8/11/2024 - Infra Tooling meeting, Agreement to close to that there are still the conditional Shalls

25/10 HL7 AU FHIR Tooling Community call: agreement to include MAY tests for search parameters only as part of Inferno AU Test kits. Reason: Some MAYs are conditional SHALLs. Those MAYs need to be tested. Other MAYs may not need testing.
